import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    padding: 24,
    marginHorizontal: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
    height: 'auto',
    maxHeight: '80%',
  },
  mainheading: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Roboto',
  },
  heading: {
    fontSize: 24,
    fontWeight: '600',
    color: '#1a6a6e',
    marginBottom: 20,
    textAlign: 'center',
    fontFamily: 'Roboto',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    paddingLeft: 40,
    fontSize: 16,
    color: '#1f2937',
    backgroundColor: '#f5f7fa',
  },
  inputFocused: {
    borderColor: '#2e8b8f',
    backgroundColor: '#fff',
  },
  icon: {
    position: 'absolute',
    left: 12,
    zIndex: 1,
  },
  button: {
    backgroundColor: '#1a6a6e',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    marginVertical: 15,
    shadowColor: '#1a6a6e',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Roboto',
  },
  forgotPassword: {
    alignItems: 'flex-end',
  },
  forgotPasswordText: {
    color: '#2e8b8f',
    fontSize: 14,
    fontWeight: '500',
  },
  signUpText: {
    color: '#2e8b8f',
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: 10,
  },
});